<div class="col_12">
<!-- Breadcrumbs -->
<ul class="breadcrumbs">
<li><a href="./index.php?page=accueil_parc">Accueil</a></li>
<li>Histoire du parc animalier</li>
</ul>
<p><a class="lightbox" href="./contenu/images/autres/_FAL3040_800x600.jpg"><img class="align-left" alt="Parc animalier des Angles, en Capcir" src="./contenu/images/autres/vignettes/_FAL3040_150x125.jpg" width="150" /></a>
Lorsqu'une idée naît dans l'esprit d'un homme, on ne sait jamais ce qu'elle adviendra. Celle qui germa voici près d'une quinzaine d'années dans la te de <strong>Laurent Balaguer</strong>, alors bûcheron à la bonne saison et « patron » de la seule station de ski privée du département, était fort modeste et n'avait pas grand chose à voir avec la création d'un parc animalier !
</p>
<p>Soucieux de valoriser sa <strong><a href="http://www.laquillane.fr/" target="blank">petite station familiale du Col de la Quillane</a></strong>, après qu'un terrible accident de travail l'eut privé de l'usage de ses jambes, il envisagea d'installer une <strong>harde de rennes</strong> comme cela s'était déjà fait dans les Alpes et le Jura.</p>
<p>Son idée était originale dans les Pyrénées, on n'y avait pas encore songé. Dans on entourage, des amis montagnards et des scientifiques étudièrent cette éventualité, et conseillèrent d'attendre des jours meilleurs …</p>
<p>A la fin des années 1980, l'idée initiale ayant fait son chemin, tant dans l'esprit de son inventeur que dans celui de <strong>son fils aîné Charles</strong>, c'est à un <strong>parc animalier</strong> installé au Col de la Quillane que l'on pense.</p>
<p><a class="lightbox" href="./contenu/images/autres/_FAL3042_800x600.jpg"><img class="align-right" alt="Parc animalier des Angles, en Capcir" src="./contenu/images/autres/vignettes/_FAL3042_150x125.jpg" width="150" /></a>
Charles Balaguer (titulaire du Certificat de Capacité délivré par le Ministère de l'Environnement permettant la gestion des espèces sauvages détenues dans le parc) travaille sur un projet avec un ensemble de partenaires très divers : le <strong>syndicat touristique du Capcir-Haut Conflent</strong>, la <strong>commune de La Llagonne</strong>, la <strong>délégation de la Chambre de Commerce et de l'Industrie de Saillagouse</strong>, l'<strong>ADEPFO</strong>, la <strong>Mutualité Agricole</strong>, l'<strong>ONF</strong>, les <strong>Directions Départementales de l'Agriculture et des Services Vétérinaires</strong>, la <strong>Fédérations des Chasseurs</strong>, ainsi qu'avec des techniciens et spécialistes concernés par la faune sauvage et l'aménagement. Parmi ces derniers ayant eu un rôle majeur dans l'avancée du projet, on peut citer : <strong>Mr D. Guérineau</strong> (Directeur du Parc de Chizé, Docteur es Sciences), <strong>Mr G. Gonzales</strong> (chercher à l'INRA), <strong>Mr D. Roques</strong> (Président national des Éleveurs de Daims), <strong>Mme F. Delcasso</strong> (Chambre de Commerce et de l'Industrie).</p>
<p><strong>Quatorze espèces</strong> devaient être installées sur les 25 hectares de la forêt communale de la Quillane. Pour divers raisons, ce site fût abandonné fin 1990 et quatre autres aires montagnardes furent alors étudiées par une commission technique : site près du lac du Passet (commune de Porte), site du Pla d'Artigues (commune de Bolquère) et sites du Pla del Mir et des Jassettes (commune des Angles).</p>
<p><a class="lightbox" href="./contenu/images/autres/Patrick_Nosetto (35)_450x600.JPG"><img alt="Loup" class="align-left" alt="Parc animalier des Angles, en Capcir" src="./contenu/images/autres/vignettes/Patrick_Nosetto (35)_115x150.JPG" /></a>
Quatre critères ont déterminé le choix : confort des animaux, intérêt paysager et touristique, facilité d'aménagement et investissement à faire.
</p>
<p>La commission a, en <strong>juillet 1991</strong>, choisi <strong>le Pla del Mir et ses 37 hectares de forêt</strong>.</p>
<p>Dès cet instant, tout va aller plus vite, avec l'<strong>aide efficace de la commune des Angles</strong>. L'<strong>association « Connaissance Animaux Pyrénéens »</strong> est créée pour d'une part apporter son concours dans le domaine de l'information et de la pédagogie et, d'autre part, pour veiller à l'éthique du parc.</p>
<p><a class="lightbox" href="./contenu/images/autres/_FAL2309_450x600.jpg"><img class="align-right" alt="Parc animalier des Angles, en Capcir" src="./contenu/images/autres/vignettes/_FAL2309_115x150.jpg" /></a>
C'est donc le <strong>20 décembre 1994</strong>, en hiver, que le parc animalier a ouvert ses portes. Les vacances de Noël, la neige, la beauté du site suspendu au dessus du plateau du Capcir, l'originalité des espèces présentées dont une harde de rennes, animaux à l'origine de l'idée créatrice, ont fait le succès que l'ont sait.</p>
<p>C'est une <strong>belle histoire</strong> d'hommes et d'animaux qui donne au Capcir et à la Montagne Catalane l'exceptionnelle possibilité de promouvoir un tourisme fondé sur une meilleure compréhension, et donc un plus grand respect du monde naturel montagnard.</p>
</div>