<div class="col_12">
<!-- Breadcrumbs -->
<ul class="breadcrumbs">
<li><a href="./index.php?page=accueil_parc">Accueil</a></li>
<li>Qu'est ce que le parc animalier ?</li>
</ul>
<div class="col_6">
<p><a class="lightbox" href="./contenu/images/parc/_FAL1952_800x600.jpg"><img class="align-left" alt="Parc animalier des Angles, en Capcir" src="./contenu/images/parc/vignettes/_FAL1952_150x125.jpg" width="150" /></a>
<strong>Qu'est ce que le parc animalier des Angles en Capcir ?</strong> Ce n'est ni un zoo avec des animaux confinés dans des espaces restreints hors du milieu naturel, ni une réserve où seraient présentes et visibles toutes les espèces pyrénéennes regroupées !</p>
<p>C'est tout d'abord un <strong>espace montagnard forestier typqique de notre région</strong> : 37 hectares de pins à crochets, situés sur un des versants orientaux du renommé massif du Carlit, entre 1700m et 1800m d'altitude, pas très loin des sources du fleuve Aude et tout à côté de la station de ski.</p>
<p>Cette portion de montagne close est divisée en enclos, presque similaire aux biotopes de chaque espèce. Le <strong>milieu naturel a été respecté</strong> le plus possible lors des travaux et des sites particuliers ont été mis en valeur. Ainsi en est il des éboulis et chaos granitiques où s'ébattent bouquetins et isards, du belvédère sommital permettant d'embrasser un extraordinaire panorama sur le Capcir, les massifs de Madres, du Cambre d'Aze et de Carança, du ruisseau que le sentier botanique suit dans ses ressauts et méandres ...</p>
<p><strong>Deux itinéraires, un long et un court</strong>, parcourent cet univers pyrénéen en réduit. chacun peut y prendre son temps, s'arrêter ou pique-niquer sur les zones aménagées, observer à loisir les animaux hébergés dans les enclos mais aussi ceux qui vivent là depuis toujours, découvrir une flore caractéristique, des arbres qui ont pris des formes curieuses, des rochers étrangement modelés par l'érosion.</p>
<p><a class="lightbox" href="./contenu/images/parc/_FAL1958_800x600.jpg"><img class="align-right" alt="Parc animalier des Angles, en Capcir" src="./contenu/images/parc/vignettes/_FAL1958_150x125.jpg" width="150" /></a>
C'est dans ce cadre tout à fait naturel que sont présentés les animaux pyrénéens actuels, vivant depuis des temps immémoriaux dans nos montagnes tels l'<strong><a href="./index.php?page=faune_pyreneenne#Isard">isard</a></strong> et le <strong><a href="./index.php?page=faune_pyreneenne#Sanglier">sanglier</a></strong>, et ceux qui ont fui les versants français comme le <strong><a href="./index.php?page=faune_pyreneenne#Bouquetin">bouquetin</a></strong> et le <strong><a href="./index.php?page=faune_pyreneenne#Loup">loup</a></strong>. Les espèces en voie de raréfaction voire de disparition comme l'<strong><a href="./index.php?page=faune_pyreneenne#Ours">ours</a></strong>, comme celles à jamais disparues du sol pyrénéen, tels le <strong><a href="./index.php?page=faune_pyreneenne#Bison">bison</a></strong> et le <strong><a href="./index.php?page=faune_pyreneenne#Renne">renne</a></strong>, sont bien à leur place dans ce parc du Capcir.</p>
<p>Les herbivores, grands ou petits, disparus au cours des siècles comme les <strong><a href="./index.php?page=faune_pyreneenne#Cerf">cerfs</a></strong>, <strong><a href="./index.php?page=faune_pyreneenne#Chevreuil">chevreuils</a></strong>, <strong><a href="./index.php?page=faune_pyreneenne#Daim">daims</a></strong>, <strong><a href="./index.php?page=faune_pyreneenne#Mouflon">mouflons</a></strong>, <strong><a href="./index.php?page=faune_pyreneenne#Marmotte">marmottes</a></strong>, et réintroduits à nouveau dans nos massifs, sont là très à leur aise.</p>
<p>Il suffit d'être patient et passionné pour observer ce <strong>peuple animal montagnard</strong> qui depuis des milliers de siècles fût sans cesse mêlé à l'histoire des hommes. L'art rupestre préhistorique des grottes ornées pyrénéennes est le témoignage de ce long parcours commun qui aujourd'hui encore se poursuit à travers la chasse, l'élevage, les loisirs, l'art, ...</p>
</div>
<div class="col_6">
<p><a class="lightbox" href="./contenu/images/parc/_FAL1955_800x600.jpg"><img class="align-right" alt="Parc animalier des Angles, en Capcir" src="./contenu/images/parc/vignettes/_FAL1955_150x125.jpg" width="150" /></a>
Les changements de saison pour ceux qui aiment la montagne sont des émerveillements permanents dans le parc, non seulement dans le parc le paysage se transforme mais les animaux aussi : chez les cervidés, <strong>les bois tombent puis repoussent</strong>, , à la période des amours, <strong>le brame du cerf</strong> et les <strong>les démonstrations herculéennes de l'ours mâle</strong> sont des spectacles impressionants, la <strong>mise bas de femelles</strong> et le <strong>vagabondage des nouveaux venus</strong> sont des instants émouvants. Il suffit alors de penser que dans la nature c'est ainsi que cela se passe, sûrement, réfléchir à ce que l'on peut faire ou ne pas faire lors d'une promenade en forêt.</p>	
<p><a class="lightbox" href="./contenu/images/parc/IMG_0093_800x600.jpg"><img class="align-left" alt="Parc animalier des Angles, en Capcir" src="./contenu/images/parc/vignettes/IMG_0093_150x125.jpg" width="150" /></a>
<p>Le parc est fait pour que <strong>chacun choisisse sa manière d'entrer en contact avec la nature et les animaux</strong>. La visite est, quand on comprend la véritable signification une incitation à mieux connaître la montagne et les espèces qui l'habitent.</p>
<p>Après, au delà des limites du parc, dans la montagne libre et sauvage, lors d'une randonnée, on percevra mieux que l'<strong>harmonie entre les hommes et les animaux</strong> est nécessaire, que le touriste que nous sommes tous un jour ou l'autr n'est pas l'unique hôte de la montagne.</p>
<p>Les <strong>enfants</strong>, plus que tous autres visiteurs, percevront l'importance des rapports qui peuvent s'instaurent entre les hommes et la nature. Le parc est peut être plus fait pour eux que pour les adultes. Mais comme l'écrivait <strong>Antoine de Saint Exupéry</strong> <blockquote class="small">Toutes les grandes personnes ont d'abord été des enfants (mais peu d'entre elles s'en souviennent).</blockquote></p>
<p><a class="lightbox" href="./contenu/images/parc/IMG_0094_800x600.jpg"><img class="align-right" alt="Parc animalier des Angles, en Capcir" src="./contenu/images/parc/vignettes/IMG_0094_150x125.jpg" width="150" /></a>
Et bien, pour mieux apprécier le parc animalier, il suffit que pour une fois elles s'en souviennent, elles ne seront pas déçues de ce <strong>retour en enfance</strong>.</p>

</div>
</div>